name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy with cleanup
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
            # Pull new image
            docker pull ghcr.io/thecodemonkey/pacman:"$IMAGE_TAG"

            # Stop and remove existing container
            docker stop pacman || true
            docker rm pacman || true

            # Run new container
            docker run -d --name pacman \
              -p 7172:80 \
              ghcr.io/thecodemonkey/pacman:"$IMAGE_TAG"

            # Cleanup old images, behalte nur die letzten 3
            # docker images -q ghcr.io/thecodemonkey/pacman | tail -n +4 | xargs -r docker rmi -f